name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Restaurar cache do Deno
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno
          key: deno-${{ runner.os }}-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            deno-${{ runner.os }}-

      - name: Baixar dependências do Deno
        run: deno cache mod.ts

      - name: Verify formatting
        run: deno fmt --check
        continue-on-error: true

      - name: Run linter
        run: deno lint
        continue-on-error: true

      - name: Run tests
        run: deno task test

      - name: Publish package
        run: deno publish
